### ISSUE TITLE
feature request: able to mark images as sensative/whatever

### ISSUE THREAD

**Issue by alien-sunset** [olafmoriarty/blue-bots-done-quick#9] opened 2024-10-29 17:10 UTC
Cheep Bots Toot Sweet allows you to either hide or show your images via tags, both for the overall bot, and for individual images.

i see that this feature is also available in bluesky, and it would be nice to be able to do so with tags in bot code as well.
(chap bots toot sweat uses {hide} and  {show} before the image)

![image](https://github.com/user-attachments/assets/bd17a66e-d678-46ef-b394-bb778f493e27)

![image](https://github.com/user-attachments/assets/ba37acbe-b092-4d2b-92db-93694b62dca9)

(having something similar to this text on the edit page for a bot on Blue Bots would be super handy as a reference, btw)

**Comment by olafmoriarty** [comment] 2024-11-02 12:04
I'm not entirely sure this would work as intended on Bluesky.

First, "sensitive" is not really a binary value on Bluesky, there are different types of sensitive media and when marking a post as sensitive you have to specify which label to add. A simple `{hide}` would therefore not be enough information for the bot, as it would need to know WHY the post should be marked as sensitive. Adding an attribute, e.g. `{hide nudity}`, would make this possible, but if the purpose of the change is to make it easier to reuse Mastodon bots, I would also have to have *something* happen when someone enters {hide} without the attribute, so then the question is which label to add.

Second, even though a post is marked as sensitive it doesn't mean it's hidden to all users. So `{hide}` wouldn't actually mean hide, which could be confusing.

***However,*** the suggestion is good, so I'm adding it to the todo-list. It won't be a priority, as especially the `{show}` part would involve a lot of work (to override the default, that means there'd have to be a way to *set* the default, too, so that's an extra database column to keep track of that).

**Comment by alien-sunset** [comment] 2024-11-02 12:12
Huh, there’s no generic reasoning at all? How odd, on mastodon people can hide media for many different reasons, which is usually listed in the content warning label if necessary,  

So on bluesky you can ONLY hide nudity? What do you do if you have a lot of followers with eating disorders and need to hid pictures of food to help them avoid triggers?
Or if you like cool bugs but are followed by a lot of arachnophobes?

**Comment by alien-sunset** [comment] 2024-11-02 12:15
I mean adding a reason shouldn’t be TOO hard, just at the moment my Remedios Varo bot has a handful of images with bare breasts that may get it into trouble if someone gets persnickety so it would even be an ‘approved’ reason

**Comment by olafmoriarty** [comment] 2024-11-02 12:46
Bluesky uses what they call "stackable" moderation services. They have a small selection of global moderation settings such as nudity, porn, graphic or suggestive, but you can also (with a TON of knowhow) create your own moderation service, that anyone can subscribe to. For example, I subscribe to a labeler that hides all AI-generated images, and there are a ton of labelers out there, but they're not available in your bluesky settings until you actually find them and subscribe to them.

Also, as a regular user, when you create a bluesky post, you can only choose one of the global labels. So if I upload an image containing porn, I can mark it as porn, but if I upload an image that is AI-generated, I cannot mark it as AI-generated. Only that labeler's moderators can do that.

When generating posts using the API, like BlueBotsDoneQuick does, it appears to be very easy to add any custom labels. However, the user who doesn't want to see food images would still need to find a labeler that hides all food images for them, they can't just add "food" to a moderation list themselves. And of course, since regular users have no "this is a food image" button, food images will only be filtered if they have been seen by that labeler's moderator, and that's assuming such a labeler exists in the first place. But in general, most labels are added by the various moderators out there, not by the users themselves.

I'm guessing a `{hide [reason]}` would be very easy to add to a bot, just beware that for most people on Bluesky the image wouldn't be hidden at all unless that reason is one of the globals.

**Comment by alien-sunset** [comment] 2024-11-02 18:33
that seems unnecessarily complicated and restrictive.
but, yet another reason why I prefer hanging out on Masto. 
I don't have to wait for someone else to make a complicated thing for me to block whatever content need or for my friends to be able to warn me about potentially triggering stuff.

**Comment by olafmoriarty** [comment] 2024-11-08 22:09
Okay, how about this:

- If you add `{hide}` or `{label}` to a post, it will be marked as "Suggestive". "Label" makes the most sense to me, but "hide" should be an alias.
- To add another label, you add a parameter to the tag: `{hide suggestive}`, `{hide nudity}`, `{hide porn}` or `{hide graphic}`. I don't think I have a practical way of adding other labels than the global ones.
- In your bot control panel you can set a default so that ALL your images are marked with the same label. To override this for a single post, you can add `{show}`.

**Comment by alien-sunset** [comment] 2024-11-09 01:12
that sounds reasonable,
cbts uses hide, so anybody porting over won't have to go through and change things, but also allowing for adding tags means we can more accurately label our content if we need.

a default setting is good too, especially with the {show} override.

**Closed** 2024-12-20 22:28 UTC
Labels: enhancement
