### ISSUE TITLE
another SVG display problem on newest bots

### ISSUE THREAD

**Issue by alien-sunset** [olafmoriarty/blue-bots-done-quick#17] opened 2024-11-09 23:13 UTC
I'm really good at breaking things apparently 😓

![image](https://github.com/user-attachments/assets/10b892e2-058f-447e-b15c-8ea30285325c)

**Comment by olafmoriarty** [comment] 2024-11-09 23:25
The database field used to store your last post for displaying in newest/popular bots, was a TEXT field, and those have a max length of 65,535 characters, which I assumed was enough. As it wasn't, the end of your code was cut off, including the closing } in your {svg} tag.

I changed it to a MEDIUMTEXT field now - those have a max length of 16 MB. I also removed the lastPostText of your bot to clear up room on the front page, but the next one your bot posts should work as intended.

**Closed** 2024-11-09 23:25 UTC
Labels: bug
