### ISSUE TITLE
img tags not parsing sometimes

### ISSUE THREAD

**Issue by fawfulthegreat** [olafmoriarty/blue-bots-done-quick#5] opened 2024-10-19 05:57 UTC
I ported a bot that i already had on Twitter using the same code (so I know for sure there were no mistakes in it), and it just made a post where one of the 4 images failed to display and instead showed the raw code for that one. I've verified the image in question is still up at the URL used. The post before that also did not attach an image that was supposed to be attached. https://bsky.app/profile/marioanything.bsky.social/post/3l6trq7hnev2u
https://bsky.app/profile/marioanything.bsky.social/post/3l6tr6bdhye2w

(for reference every character that the bot names also pulls an image, so there should be an image for Baby Daisy in the second one too)

**Comment by olafmoriarty** [comment] 2024-10-19 10:19
Thanks for the report. There are (at least) two different issues here.

The Goombario issue is that the character after "img" in {img https://i.imgur.com/TeCs1by.jpg} is not a normal space, but a non-breaking space, and the regex only checks for normal spaces. (I checked your code, and that's the case for two of your characters - Goombario and Bobby). I hadn't predicted that anyone would use a non-breaking space there and therefore didn't add it to the regular expression. I have no idea why CBDQ would support this as it doesn't make much sense to me, but it's an easy fix, so I'll add support for non-breaking spaces in image tags later today.

As for why the Baby Daisy image doesn't load, I haven't figured that out yet. My first assumption was that the image for some reason could not be uploaded to Bluesky, but that does not appear to be the case, so I'll look further into the issue and see what I can find out.

**Comment by fawfulthegreat** [comment] 2024-10-19 20:41
It just happened with Fun Gus too. While Baby Daisy has worked on other occasions. I hope it's not just a random chance it fails to load an image.

**Comment by olafmoriarty** [comment] 2024-11-02 08:16
The problem appears to not happen anymore, so I'll make the assumption that the cause was a temporary hiccup in Bluesky and close this issue now. Thanks for reporting it.

**Closed by olafmoriarty** 2024-11-02 08:16 UTC
